---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: default
  source:
    path: clusters
    repoURL: git@github.com:rh-dttl-edge-virt-demo/managed-clusters.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
