---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.cluster.name }}-api
spec:
  dnsNames:
    - api.{{ .Values.cluster.name }}.{{ .Values.cluster.baseDomain }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Values.cluster.name }}-api-cert
