---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ .Values.cluster.name }}-certificates-managed
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-12 Cryptographic Key Establishment and Management
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: router-certificate
        spec:
          remediationAction: enforce
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: router-cert
                  namespace: openshift-ingress
                type: kubernetes.io/tls
                data:
                  tls.crt: >-
                    {{ "{{" }}hub (index (lookup "v1" "Secret" "{{ .Values.cluster.env }}" "{{ .Values.cluster.name }}-router-cert").data "tls.crt") | protect hub{{ "}}" }}
                  tls.key: >-
                    {{ "{{" }}hub (index (lookup "v1" "Secret" "{{ .Values.cluster.env }}" "{{ .Values.cluster.name }}-router-cert").data "tls.key") | protect hub{{ "}}" }}
            - complianceType: musthave
              objectDefinition:
                apiVersion: operator.openshift.io/v1
                kind: IngressController
                metadata:
                  name: default
                  namespace: openshift-ingress-operator
                spec:
                  defaultCertificate:
                    name: router-cert
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: api-certificate
        spec:
          remediationAction: enforce
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: APIServer
                metadata:
                  name: cluster
                spec:
                  servingCerts:
                    namedCertificates:
                      - names:
                          - api.{{ .Values.cluster.name }}.{{ .Values.cluster.baseDomain }}
                        servingCertificate:
                          name: openshift-api
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: openshift-api
                  namespace: openshift-config
                type: kubernetes.io/tls
                data:
                  tls.crt: >-
                    {{ "{{" }}hub (index (lookup "v1" "Secret" "{{ .Values.cluster.env }}" "{{ .Values.cluster.name }}-api-cert").data "tls.crt") | protect hub{{ "}}" }}
                  tls.key: >-
                    {{ "{{" }}hub (index (lookup "v1" "Secret" "{{ .Values.cluster.env }}" "{{ .Values.cluster.name }}-api-cert").data "tls.key") | protect hub{{ "}}" }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .Values.cluster.name }}
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: {{ .Values.cluster.name }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .Values.cluster.name }}-certificates-managed
placementRef:
  name: {{ .Values.cluster.name }}
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: {{ .Values.cluster.name }}-certificates-managed
    apiGroup: policy.open-cluster-management.io
    kind: Policy
