---
apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: {{ .Values.cluster.name }}
spec:
  platformType: {{ .Values.cluster.platformType }}
  {{- with .Values.cluster.platform }}
  platform:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  imageSetRef:
    name: img{{ .Values.cluster.version }}-{{ .Values.cluster.arch }}-appsub
  networking:
    {{- toYaml .Values.cluster.networking | nindent 4 }}
  provisionRequirements:
    controlPlaneAgents: {{ .Values.cluster.controlPlaneNodes }}
  sshPublicKey: {{ .Values.sshKey }}
