---
apiVersion: batch/v1
kind: Job
metadata:
  name: update-manifests
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 4
  template:
    spec:
      serviceAccount: update-manifests
      serviceAccountName: update-manifests
      restartPolicy: Never
      containers:
        - name: update-manifests
          image: image-registry.openshift-image-registry.svc:5000/openshift/tools:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args:
            - -xe
            - /app/update-manifests.sh
          volumeMounts:
            - name: update-manifests
              mountPath: /app
      volumes:
        - name: update-manifests
          configMap:
            name: update-manifests
            defaultMode: 493
