{{- if .Values.certificates.api.managed -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
spec:
  dnsNames:
    {{- toYaml .Values.certificates.api.dnsNames | nindent 4 }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  secretName: openshift-api
---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
          {{- toYaml .Values.certificates.api.dnsNames | nindent 10 }}
        servingCertificate:
          name: openshift-api
{{- end }}
