{{- define "le.solvers" -}}
{{- range $solver := .Values.letsEncrypt.solvers -}}
{{- if eq $solver.type "dns" -}}
- dns01:
    {{- toYaml $solver.dnsConfig | nindent 4 }}
  {{- with $solver.dnsZones }}
  selector:
    dnsZones:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- else if eq $solver.type "http" }}
- http01:
    ingress:
      ingressClassName: {{ $solver.ingressClassName }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  acme:
    email: {{ .Values.letsEncrypt.email }}
    preferredChain: {{ toYaml .Values.letsEncrypt.preferredChain }}
    privateKeySecretRef:
      name: letsencrypt-privatekey
    server: {{ .Values.letsEncrypt.server }}
    solvers:
    {{- include "le.solvers" . | nindent 4 }}
