{{- range $secret := .Values.letsEncrypt.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  {{- toYaml $secret.stringData | nindent 2 }}
{{- end }}
