{{- range $name, $acme := .Values.acme }}
{{- range $secret := $acme.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: acme-{{ $name }}-{{ $secret.name }}
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
{{- range $name, $value := $secret.stringData }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- range $name, $value := $secret.data }}
  {{ $name }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
