---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: cluster
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: {{ .Values.cluster.name }}
