---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    deployOVS: "false"
  name: kubevirt-hyperconverged
spec:
  {{- with .Values.hyperconverged }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
