apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
spec:
  databaseStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.agentServiceConfig.databaseStorage }}
  filesystemStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.agentServiceConfig.filesystemStorage }}
  imageStorage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.agentServiceConfig.imageStorage }}
